version: "3.8"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: wordpress
    restart: always
    ports:
      - "8081:80"

  wordpress:
    depends_on:
      - db
    image: wordpress:6.5.4-php8.1-apache
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
